name: Reza Jatnika
title: Reza Jatnika
url: http://reza.re
markdown: rdiscount

permalink: /blog/:year/:month/:day/:title/
paginate: 5
pygments: true
exclude: ['README.md', 'Rakefile', 'jekyll.thor', 'Procfile']
