# Site settings
name:  Reza Jatnika
email: rezajatnika@gmail.com
title: Reza Jatnika

twitter_username: rezajatnika
github_username:  rezajatnika

url: https://rezajatnika.github.io/

baseurl: ""
highlighter: pygments
markdown: redcarpet
exclude: ['README.md', 'Rakefile', 'jekyll.thor']
